import type { SkellyDocsConfig } from '@freemocap/skellydocs';

const config: SkellyDocsConfig = {
  hero: {
    title: 'FreeMoCap',
    accentedSuffix: 'Validation',
    subtitle: 'Validation and reproducibility',
    tagline:
      'Data, analysis pipelines, and reproducible results for evaluating FreeMoCap against marker-based motion capture.',
    logoSrc: '/validation/img/logo.svg',
    parentProject: {
      name: 'FreeMoCap',
      url: 'https://freemocap.org',
    },
    ctaButtons: [
      { label: 'Reproduce the Study', to: '/docs/getting-started/reproduction', variant: 'primary' },
      { label: 'View on GitHub', to: 'https://github.com/freemocap/validation', variant: 'secondary' },
    ],
  },

  features: [
    {
      id: 'validation-dataset',
      icon: '📊',
      title: 'Validation Dataset',
      description:
        'Public 3D trajectory data from treadmill gait and standing balance validation.',
      summary: (
        <>
          Explore aligned 3D trajectories from FreeMoCap pose-estimation
          pipelines and the corresponding marker-based Qualisys reference.
        </>
      ),
      issues: [],
      docPath: 'getting-started/dataset',
    },
    {
      id: 'analysis-pipeline',
      icon: '⚙️',
      title: 'Analysis Pipeline',
      description:
        'Reproducible gait and balance analyses built from the released validation data.',
      summary: (
        <>
          Follow the processing pipeline from aligned trajectories through
          gait, balance, and agreement analyses.
        </>
      ),
      issues: [],
      docPath: 'pipeline/overview',
    },
    {
      id: 'figures-tables',
      icon: '📈',
      title: 'Figures & Tables',
      description:
        'Regenerate the study-level figures, tables, and statistical results.',
      summary: (
        <>
          Reproduce the outputs reported in the validation study from the
          analysis artifacts generated by the pipeline.
        </>
      ),
      issues: [],
      docPath: 'getting-started/reproduction',
    },
  ],

  guaranteesConfig: {
    title: (
      <>
        Built for <span style={{ color: 'var(--sk-accent)' }}>reproducibility</span>
      </>
    ),
    items: [
      'Publicly archived validation data',
      'Version-controlled analysis code',
      'Reproducible gait and balance analyses',
      'Regenerable study figures and tables',
    ],
    issues: [],
  },
};

export default config;