from validation.components import FREEMOCAP_PARQUET, QUALISYS_PARQUET, FREEMOCAP_BALANCE_METRICS, QUALISYS_BALANCE_METRICS, FREEMOCAP_BALANCE_VELOCITIES, QUALISYS_BALANCE_VELOCITIES

REQUIRES = [QUALISYS_PARQUET, FREEMOCAP_PARQUET]

PRODUCES = [FREEMOCAP_BALANCE_METRICS, QUALISYS_BALANCE_METRICS, FREEMOCAP_BALANCE_VELOCITIES, QUALISYS_BALANCE_VELOCITIES]