
trial_path: sub-002/task-treadmill_trial-01

trackers:
- mediapipe
- vitpose
- rtmpose

pipeline:
- JointAnglesStep
- StepFinderStep
- GaitParametersStep
- TrajectoryStridesStep
- JointAnglesStridesStep
- RMSEStep

ProjectConfig:
  qualisys_model_info_path: C:\Users\aaron\Documents\GitHub\freemocap_validation\qualisys_markerset\qualisys_model_info.yaml
  conditions:
    speed_0_5:
      frames: [660,1260]
    speed_1_0:
      frames: [1650,2250]
    speed_1_5:
      frames: [2700,3300]
    speed_2_0:
      frames: [3700,4300]


TemporalAlignmentStep:
  start_frame: null
  end_frame: null
  qualisys_joint_weights_file: qualisys_joint_weights/validation_study_weights.yaml

SpatialAlignmentStep:
  markers_for_alignment:
  - left_shoulder
  - right_shoulder
  - left_elbow
  - right_elbow
  - left_wrist
  - right_wrist
  - left_hip
  - right_hip
  - left_knee
  - right_knee
  - left_ankle
  - right_ankle
  - left_heel
  - right_heel
  - left_foot_index
  - right_foot_index
  frames_to_sample: 20
  max_iterations: 100
  inlier_threshold: 40

JointAnglesStep:
  neutral_frames: [150, 340]

StepFinderStep:
  sampling_rate: 30.0
  frames_of_interest: [660, 5500]

TrajectoryStridesStep:
  loop_over_conditions: true

JointAnglesStridesStep:
  loop_over_conditions: true

RMSEStep:
  loop_over_conditions: true
  markers_for_comparison:
  - left_shoulder
  - right_shoulder
  - left_elbow
  - right_elbow
  - left_wrist
  - right_wrist
  - left_hip
  - right_hip
  - left_knee
  - right_knee
  - left_ankle
  - right_ankle
  - left_heel
  - right_heel
  - left_foot_index
  - right_foot_index

GaitParametersStep:
  loop_over_conditions: true
  sampling_rate: 30.0
