from validation.components import (
    FREEMOCAP_PARQUET,
    QUALISYS_PARQUET,
    FREEMOCAP_GAIT_EVENTS,
    QUALISYS_GAIT_EVENTS,
    FREEMOCAP_JOINT_ANGLES,
    QUALISYS_JOINT_ANGLES,
    FREEMOCAP_JOINT_ANGLE_CYCLES,
    QUALISYS_JOINT_ANGLE_CYCLES,
    FREEMOCAP_JOINT_ANGLE_SUMMARY_STATS,
    QUALISYS_JOINT_ANGLE_SUMMARY_STATS,
    POSITIONRMSE,
    VELOCITYRMSE,
    FREEMOCAP_TRAJECTORY_CYCLES,
    QUALISYS_TRAJECTORY_CYCLES,
    FREEMOCAP_TRAJECTORY_SUMMARY_STATS,
    QUALISYS_TRAJECTORY_SUMMARY_STATS,
    TRAJECTORY_RMSE_STATS,
    JOINT_ANGLE_RMSE_STATS,
    QUALISYS_GAIT_METRICS,
    QUALISYS_GAIT_SUMMARY_STATS,
    FREEMOCAP_GAIT_METRICS,
    FREEMOCAP_GAIT_SUMMARY_STATS,
    FREEMOCAP_BALANCE_METRICS,
    QUALISYS_BALANCE_METRICS,
    FREEMOCAP_BALANCE_VELOCITIES,
    QUALISYS_BALANCE_VELOCITIES
)
from validation.datatypes.data_component import DataComponent





BALANCE = {
    "synced_data": [
        FREEMOCAP_PARQUET,
        QUALISYS_PARQUET,
    ],
    "com_analysis": [
        FREEMOCAP_BALANCE_METRICS,
        QUALISYS_BALANCE_METRICS,
        FREEMOCAP_BALANCE_VELOCITIES,
        QUALISYS_BALANCE_VELOCITIES,

    ],
}


TREADMILL = {
    "synced_data": [
        FREEMOCAP_PARQUET,
        QUALISYS_PARQUET,
    ],
    "gait_events": [
        FREEMOCAP_GAIT_EVENTS,
        QUALISYS_GAIT_EVENTS,
    ],
    "gait_metrics": [
        QUALISYS_GAIT_METRICS,
        QUALISYS_GAIT_SUMMARY_STATS,
        FREEMOCAP_GAIT_METRICS,
        FREEMOCAP_GAIT_SUMMARY_STATS,
    ],
    "joint_angles": [
        FREEMOCAP_JOINT_ANGLES,
        QUALISYS_JOINT_ANGLES,
    ],
    "joint_angles_per_stride": [
        FREEMOCAP_JOINT_ANGLE_CYCLES,
        QUALISYS_JOINT_ANGLE_CYCLES,
        FREEMOCAP_JOINT_ANGLE_SUMMARY_STATS,
        QUALISYS_JOINT_ANGLE_SUMMARY_STATS,
        JOINT_ANGLE_RMSE_STATS,
    ],
    "rmse_metrics": [
        POSITIONRMSE,
        VELOCITYRMSE,
    ],
    "trajectories_per_stride": [
        FREEMOCAP_TRAJECTORY_CYCLES,
        QUALISYS_TRAJECTORY_CYCLES,
        FREEMOCAP_TRAJECTORY_SUMMARY_STATS,
        QUALISYS_TRAJECTORY_SUMMARY_STATS,
        TRAJECTORY_RMSE_STATS,
    ],
}