from validation.components import  QUALISYS_PARQUET, FREEMOCAP_PARQUET, POSITIONABSOLUTEERROR, POSITIONRMSE, VELOCITYRMSE, VELOCITYABSOLUTEERROR, FREEMOCAP_PARQUET

REQUIRES = [QUALISYS_PARQUET,FREEMOCAP_PARQUET]
PRODUCES = [POSITIONABSOLUTEERROR,POSITIONRMSE, VELOCITYABSOLUTEERROR, VELOCITYRMSE]