from validation.components import FREEMOCAP_PARQUET, QUALISYS_PARQUET, FREEMOCAP_JOINT_ANGLES, QUALISYS_JOINT_ANGLES

REQUIRES = [QUALISYS_PARQUET, FREEMOCAP_PARQUET]
PRODUCES = [FREEMOCAP_JOINT_ANGLES, QUALISYS_JOINT_ANGLES]